/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'katie' at '4/2/16 4:56 PM' with Gradle 2.12
 *
 * @author katie, @date 4/2/16 4:56 PM
 */
public class %{class_name} {
    public boolean some%{class_name}Method() {
        return true;
    }
}
