import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'katie' at '4/2/16 4:56 PM' with Gradle 2.12
 *
 * @author katie, @date 4/2/16 4:56 PM
 */
public class %{class_name} {
    @Test public void testSome%{class_name}Method() {
        %{class_name} instance = new %{class_name}();
        assertTrue("some%{class_name}Method() should return 'true'", instance.some%{class_name}Method());
    }
}
